name: Build Python Wheel

on:
  push:
    branches: ["main", "master"]
  pull_request:

jobs:
  build-wheel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build wheel
        run: |
          python -m build --wheel

      - name: List dist files
        run: |
          ls -lh dist
